services:
  app:
    build: .
    container_name: multi-tier-caching-example
    image: multi-tier-caching-example:latest
    environment:
      DATABASE_DSN: postgres://user:password@postgres_db:5432/mydb
      LOG_LEVEL: info
      REDIS_ADDR: redis_cache:6379
      REDIS_PASSWORD: ""
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      memcached:
        condition: service_started

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
